[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd ../.. && pnpm install --frozen-lockfile --filter=server..."
]

[phases.build]
cmds = [
  "cd server && pnpm prisma generate",
  "cd server && pnpm build"
]

[start]
cmd = "cd server && pnpm start:prod"

